### PR TITLE
Added "issue 10", and presence cooldown

### PR DESCRIPTION
**Pull request by hemisemidemipresent**
Changes:
- "omelette" removes an egg count
- discord does not like bots changing their presence frequently, so a cool-down has been put in place of 5 minutes between each update

note: you unfortunately have  to wait 5 minutes for the first status update to appear. This hopefully will be resolved in a future update

hope you like these changes

### CODE REVIEW

**Comment by tristan-f-r** [comment]
Hm, the egg bot doesnt speak words, maybe make the eggCount command `🥚?`?

**Comment by tristan-f-r** [comment]
A typical conversation can go
User: 🥚 
Bot: _adds one to egg_
User: 🥚 ?
Bot: 500 🥚 
User: 🍴 
Bot: _Reacts 🍴  and removes an egg_
User: 🥚
Bot: _Reacts 🥚 and adds an egg_

**Comment by hemisemidemipresent** [comment]
alright, I'll try and cook something up

**Comment by hemisemidemipresent** [comment]
@LeoDog896 yeah thats done btw

**Comment by tristan-f-r** [comment]
Perfect

**Comment by WilloIzCitron** [comment]
now anuke use nim instead js

**Pull request closed without merging**
